# Theme of the website, using dark mode
theme: minima
minima:
  skin: dark
  
# Basic info
title: DaruMeik's blog
author: DaruMeik

# Default config
baseurl: "/PersonalBlog"
permalink: none

languages: ["en", "vi"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: en
languageNames:
  vi: Vietnamese
  en: English
